### ISSUE TITLE
I could be filter the entitlements and the entitlement packs of a service 

### ISSUE THREAD

**Issue by dorion** [hexaaproject/hexaa-gui#2]
In our services are contain many number of entitlements and entitlements packs. So hard to find an concrete item over ten quantity to manage them. It will very helpful if it possible to filter by name on top of the list page.

Thanks

**Comment by bkotyik** [comment]
Hello @dorion !

Thank you for your feedback. We are working on the enhancement you requested. I will notify you when the new build goes live.

**Comment by burgosz** [comment]
dorion, somke

**Comment by bkotyik** [comment]
Hello

New release (0.26.6) has been pushed to the repository. Please update your application.
If It does not solve your problem, please reopen an issue.

Thank you for your patience.
