### ISSUE TITLE
I can't accept an invitation if I have an active Shib session

### ISSUE THREAD

**Issue by dorion** [hexaaproject/hexaa-gui#3]
When I give an invitation and I click the accept link which opened in the browser where I have a shib session, I gave back this error message:

```
The following issue has been detected: HTTP/1.1 401 Unauthorized
Date: Tue, 20 Oct 2015 08:32:09 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.45-0+deb7u1
Cache-Control: no-cache
Allow: GET
Content-Length: 51
Content-Type: application/json

{"code":401,"message":"Unauthorized","errors":null}
```

If I open the link in the other browser or destroy my shib session the workflow is working.

**Comment by solazs** [comment]
Sorry for taking so long to answer.
Is this still an issue? I believe we had a pretty big update since.
Do you also have a hexaa cookie, or just a shib session?

**Comment by bkotyik** [comment]
Hello

New release (0.26.6) has been pushed to the repository. Please update your application.
If It does not solve your problem, please reopen an issue.

Thank you for your patience.
