### ISSUE TITLE
Profile > Consent no pagionation buttons

### ISSUE THREAD

**Issue by szabogyula** [hexaaproject/hexaa-gui#4]
There is no pagination buttons (results per page) and empty pages from second page.

Video:
https://d.niif.hu/index.php/s/vKnymnqxQDOLfhl

**Comment by solazs** [comment]
Seems like a frontend issue to me (checked on the live version), ping @bkotyik

**Comment by bkotyik** [comment]
Thank you for your feedback! We have fixed the issue. The new build is currently under test on our internal server. I will notify you as soon as the new build is released.
Thank you for your patience.
