### ISSUE TITLE
Connect service to Org choose Role

### ISSUE THREAD

**Issue by szabogyula** [hexaaproject/hexaa-gui#5]
When I connect a service to an Organization, should get a select to which Role should be link what Permission.

If it make too difficult form ( permissions X roles), should pop up an alert, that warning to remember link permissions to roles.

**Comment by bkotyik** [comment]
Hello @szabogyula !

The feature you requested is implemented in frontend version 0.27.0.
We are still testing this build on our internal server, please be patient until the public release.
